wip: Flattening in name lookup
This is the 1st commit message:

squash: WIP: Flattening in name lookup

squash: Remove superfluous parent arguments

This is the commit message #2:

squash: Remove incorrect xFail

This is the commit message #3:

squash: Don't remove imports from extends nodes

We had previously removed imports from extends instances, but that would
mean that references inside the instance to imported names would not be
found. We only want to prevent enclosing instances to find imported
names inside contained extends instances which is accomplished by
`search_import=False` inside `_find_inherited`.

This is the commit message #4:

squash: Add class_modification to _apply_modifications

This allows unification of application of class_modifications.

Also remove unneeded element argument to function.

This is the commit message #5:

fix: Was adding new_class to parent.classes twice

It was already added in _instantiate_partially immediately above.

This is the commit message #6:

squash: Add _update_class_modification_scopes

In place of removed `_update_modification_argument_scopes`.

Change `_instantiate_extends_single` to use new one to make more DRY with
`Symbol.class_modification`.

TODO: Look into consolidating further by instantiating extends partially
to use the common modification handling code.

This is the commit message #7:

fix: Check .fully_instantiated in _instantiate_extends

This is the commit message #8:

fix: Need to use ast_ref for messages in _instantiate_extends

Because extends nodes are unnamed (name="").

This is the commit message #9:

fix: Properly check for builtin single extend

Add the check of ""When extending a built-in class (Real, Integer, ...)
you cannot extend other classes as well" to `_instantiate_extends` where
the other related checks are done.

We allow extending from the same built-in more than once which may be OK
if they are identical (section 5.6.1.4 The inherited contents of the
element) "At the end, the current instance is checked whether their
children (including children of extends-clauses) with the same name are
identical and only the first one of them is kept. It is an error if they
are not identical."

This is the commit message #10:

squash: Add partial instantiation of extends clause

This is the commit message #11:

tree: Add redeclare checks and checks TODO

Disallow redeclare of constant or final elements.

Put off the more difficult checks of sub-type rules and not allowing
changing of public/protected.

This is the commit message #12:

squash: _apply_redeclares FIXME (comment/whitespace only change)

This is the commit message #13:

squash: _instantiate_class: Return immediately after redeclare

This is the commit message #14:

fix: ast: ClassModificationArgument.scope setting in parser

Type is ast.Class from the parser, InstanceClass during instantiaton.

squash: WIP: Partially instantiate ExtendsClause

fix: _apply_redeclares parent_instance can be InstanceTree

This is the commit message #2:

squash: Partially instantiate ExtendsClause

This is the commit message #2:

squash: WIP: More partial instantiation

wip/drop?: Instantiate in place in _find_name

Started implementing `instantiate_in_place` in `_find_name`, but realized
that we have something like this in `_flatten_class`/`_resolve_name`
that just probably needs fixing so that we get a correctly flattened
first in `_flatten_first_and_find_rest`.

This is the commit message #2:

squash: fix _update_class_modification_scopes

Don't make unnecesary copies of the element when class modification
arguments have not changed.

Simplify logic since we always have at least an empty ClassModification
now instead of the possiblity of None.

This is the commit message #3:

wip: Temporary flattening in name lookup

Create temporary instance tree during temporary flattening.

Add an attribute to instance classes to keep track of state during the
temporary flattening recursion.

Change flatten_instance to maintain instance tree parent/child for
flattening in name lookup.

TODO: Still fails 24 tests:
=========================== short test summary info ============================
FAILED test/parse_test.py::ParseTest::test_custom_units - AssertionError
FAILED test/parse_test.py::ParseTest::test_constant_references - AttributeErr...
FAILED test/name_lookup_test.py::ImportedNameLookupTest::test_unqualified_import_non_package
FAILED test/parse_test.py::ParseTest::test_flattening_inheritance_tree - Asse...
FAILED test/parse_test.py::ParseTest::test_flattening_redeclare_nested_class
FAILED test/parse_test.py::ParseTest::test_flattening_modification_scope - At...
FAILED test/parse_test.py::ParseTest::test_flattening_redeclare_class_extends
FAILED test/parse_test.py::ParseTest::test_instantiation_lookup_scope - Attri...
FAILED test/parse_test.py::ParseTest::test_instantiation_modification_scope_spec_example
FAILED test/name_lookup_test.py::ImportedNameLookupTest::test_unqualified_import_priority
FAILED test/parse_test.py::ParseTest::test_lookup_needs_instantiation - Attri...
FAILED test/parse_test.py::ParseTest::test_nested_symbol_modifier - Assertion...
FAILED test/parse_test.py::ParseTest::test_redeclaration_scope_alternative - ...
FAILED test/parse_test.py::ParseTest::test_redeclaration_scope - AssertionErr...
FAILED test/parse_test.py::ParseTest::test_redeclare_class - AssertionError: ...
FAILED test/parse_test.py::ParseTest::test_redeclare_component_in_declaration
FAILED test/parse_test.py::ParseTest::test_redeclare_component_complicated - ...
FAILED test/parse_test.py::ParseTest::test_redeclare_components - AttributeEr...
FAILED test/parse_test.py::ParseTest::test_redeclare_component_in_extends - A...
FAILED test/parse_test.py::ParseTest::test_redeclare_component_type_compatibility
FAILED test/parse_test.py::ParseTest::test_redeclare_nonreplaceable - Asserti...
FAILED test/parse_test.py::ParseTest::test_msl_opamp_units - AttributeError: ...
FAILED test/parse_test.py::ParseTest::test_nested_classes - AssertionError: 1...
FAILED test/parse_test.py::ParseTest::test_msl_flange_units - AttributeError:...
====== 24 failed, 203 passed, 13 skipped, 7 xfailed, 21 warnings in 4.77s ======

This is the commit message #4:

try: Attempted fix gives infinite recursion

Trying to fix the following:
Were using partially instantiated to instance to lookup child class that
wasn't populated, so not found in instance tree, found in AST.

This is the commit message #5:

try: Recursive partial instantiation for name lookup

For the `find_rest` part after `_flatten_first`.

Current test failures:
=========================== short test summary info ============================
FAILED test/name_lookup_test.py::ImportedNameLookupTest::test_recursive - Ass...
FAILED test/name_lookup_test.py::ImportedNameLookupTest::test_unqualified_import_non_package
FAILED test/name_lookup_test.py::ImportedNameLookupTest::test_unqualified_import_priority
FAILED test/parse_test.py::ParseTest::test_constant_references - NotImplement...
FAILED test/parse_test.py::ParseTest::test_extends_transitively_nonreplaceable_error
FAILED test/parse_test.py::ParseTest::test_custom_units - AssertionError
FAILED test/parse_test.py::ParseTest::test_flattening_inheritance_tree - Asse...
FAILED test/parse_test.py::ParseTest::test_flattening_modification_scope - At...
FAILED test/parse_test.py::ParseTest::test_flattening_redeclare_class_extends
FAILED test/parse_test.py::ParseTest::test_derived_type_value_modification - ...
FAILED test/parse_test.py::ParseTest::test_instantiation_lookup_scope_with_modifications
FAILED test/parse_test.py::ParseTest::test_instantiation_modification_scope_spec_example
FAILED test/parse_test.py::ParseTest::test_lookup_needs_instantiation - pymoc...
FAILED test/parse_test.py::ParseTest::test_nested_classes - AssertionError: 1...
FAILED test/parse_test.py::ParseTest::test_flattening_redeclare_nested_class
FAILED test/parse_test.py::ParseTest::test_nested_symbol_modifier - Assertion...
FAILED test/parse_test.py::ParseTest::test_redeclaration_scope - AssertionErr...
FAILED test/parse_test.py::ParseTest::test_redeclare_class - AssertionError: ...
FAILED test/parse_test.py::ParseTest::test_redeclaration_scope_alternative - ...
FAILED test/parse_test.py::ParseTest::test_redeclare_component_in_extends - A...
FAILED test/parse_test.py::ParseTest::test_redeclare_component_in_declaration
FAILED test/parse_test.py::ParseTest::test_redeclare_nonreplaceable - Asserti...
FAILED test/parse_test.py::ParseTest::test_redeclare_component_complicated - ...
FAILED test/parse_test.py::ParseTest::test_redeclare_component_type_compatibility
FAILED test/parse_test.py::ParseTest::test_redeclare_components - AttributeEr...
FAILED test/parse_test.py::ParseTest::test_msl3_twopin_units - RecursionError...
FAILED test/parse_test.py::ParseTest::test_msl_opamp_units - RecursionError: ...
====== 27 failed, 200 passed, 13 skipped, 7 xfailed, 21 warnings in 4.74s ======

squash: Add partial instantiation of extends clause

This is a squash of multiple commits but I didn't retain the comments
unfortunately.