WIP: Try speedy-antlr (currently get clang error)
Try using https://github.com/amykyta3/speedy-antlr-tool.git
to speed up ANTLR parser which is currently taking majority of
parse+flatten time.

Currently gettig compilation error:
```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/rutanwk/opt/miniconda3/envs/pymoca-antlr49/include -arch x86_64 -I/Users/rutanwk/opt/miniconda3/envs/pymoca-antlr49/include -fPIC -O2 -isystem /Users/rutanwk/opt/miniconda3/envs/pymoca-antlr49/include -arch x86_64 -Isrc/pymoca/generated/cpp_src/antlr4-cpp-runtime -I/Users/rutanwk/opt/miniconda3/envs/pymoca-antlr49/include/python3.9 -c src/pymoca/generated/cpp_src/sa_modelica_translator.cpp -o build/temp.macosx-10.9-x86_64-3.9/src/pymoca/generated/cpp_src/sa_modelica_translator.o -std=c++11
src/pymoca/generated/cpp_src/sa_modelica_translator.cpp:539:49: error: no member named '_expression' in 'ModelicaParser::If_equationContext'
        {"_expression", static_cast<void*>(ctx->_expression)},
                                           ~~~  ^
src/pymoca/generated/cpp_src/sa_modelica_translator.cpp:540:53: error: no member named '_equation_block' in 'ModelicaParser::If_equationContext'
        {"_equation_block", static_cast<void*>(ctx->_equation_block)}
                                               ~~~  ^
src/pymoca/generated/cpp_src/sa_modelica_translator.cpp:549:49: error: no member named '_expression' in 'ModelicaParser::If_statementContext'
        {"_expression", static_cast<void*>(ctx->_expression)},
                                           ~~~  ^
src/pymoca/generated/cpp_src/sa_modelica_translator.cpp:550:54: error: no member named '_statement_block' in 'ModelicaParser::If_statementContext'
        {"_statement_block", static_cast<void*>(ctx->_statement_block)}
                                                ~~~  ^
src/pymoca/generated/cpp_src/sa_modelica_translator.cpp:601:49: error: no member named '_expression' in 'ModelicaParser::When_equationContext'
        {"_expression", static_cast<void*>(ctx->_expression)},
                                           ~~~  ^
src/pymoca/generated/cpp_src/sa_modelica_translator.cpp:602:53: error: no member named '_equation_block' in 'ModelicaParser::When_equationContext'
        {"_equation_block", static_cast<void*>(ctx->_equation_block)}
                                               ~~~  ^
src/pymoca/generated/cpp_src/sa_modelica_translator.cpp:611:49: error: no member named '_expression' in 'ModelicaParser::When_statementContext'
        {"_expression", static_cast<void*>(ctx->_expression)},
                                           ~~~  ^
src/pymoca/generated/cpp_src/sa_modelica_translator.cpp:612:54: error: no member named '_statement_block' in 'ModelicaParser::When_statementContext'
        {"_statement_block", static_cast<void*>(ctx->_statement_block)}
                                                ~~~  ^
src/pymoca/generated/cpp_src/sa_modelica_translator.cpp:627:49: error: no member named '_expression' in 'ModelicaParser::Expression_ifContext'
        {"_expression", static_cast<void*>(ctx->_expression)}
                                           ~~~  ^
9 errors generated.
```