wip: Propagate name lookup args for recursion
Trying to fix infinite recursion problem for
test_unqualified_import_non_package by propagating all name lookup
args at all levels of name lookup, but still is an issue because we are
recursing through instantiation that loses the arg values.

Infinite recursion is only in the following tests:
- test_unqualified_import_non_package
- test_msl3_twopin_units
- test_msl_flange_units
- test_msl_opamp_units

Current status of tests:
===================================================================== short test summary info =====================================================================
FAILED test/name_lookup_test.py::ImportedNameLookupTest::test_unqualified_import_non_package - RecursionError: maximum recursion depth exceeded
FAILED test/parse_test.py::ParseTest::test_constant_references - pymoca.tree.NameLookupError: Non-constant Symbol found in enclosing class
FAILED test/parse_test.py::ParseTest::test_error_extends_class_also_extended_name_nested - AssertionError: ModelicaSemanticError not raised
FAILED test/parse_test.py::ParseTest::test_extends_order - NotImplementedError: Expression modifications not implemented yet
FAILED test/parse_test.py::ParseTest::test_flattening_inheritance_tree - AssertionError: 'l2.c' not found in OrderedDict({'w': InstanceSymbol(name='w', ast_ref=Symbol(name='Real', type='Real'), modification_environment=ClassModific...
FAILED test/parse_test.py::ParseTest::test_flattening_modification_scope - NotImplementedError: Expression modifications not implemented yet
FAILED test/parse_test.py::ParseTest::test_flattening_redeclare_class_extends - AssertionError: "TODO: FILL IN ERROR MESSAGE" does not match "In P.PartialMedium extends BaseProperties, BaseProperties and parents cannot be replaceable"
FAILED test/parse_test.py::ParseTest::test_flattening_redeclare_nested_class - AssertionError: -10 != 0.0 : for at.m
FAILED test/parse_test.py::ParseTest::test_lookup_needs_instantiation - pymoca.tree.NameLookupError: Type A.C.T of symbol x not found in MyModel
FAILED test/parse_test.py::ParseTest::test_msl3_twopin_units - RecursionError: maximum recursion depth exceeded
FAILED test/parse_test.py::ParseTest::test_msl_flange_units - RecursionError: maximum recursion depth exceeded
FAILED test/parse_test.py::ParseTest::test_msl_opamp_units - RecursionError: maximum recursion depth exceeded
FAILED test/parse_test.py::ParseTest::test_redeclaration_scope - AssertionError: 'Z' not found in OrderedDict()
FAILED test/parse_test.py::ParseTest::test_redeclaration_scope_alternative - AssertionError: 'Z' not found in OrderedDict()
FAILED test/parse_test.py::ParseTest::test_redeclare_class - AssertionError: 'BoolType' != 'Boolean'
FAILED test/parse_test.py::ParseTest::test_redeclare_component_complicated - AttributeError: 'ComponentRef' object has no attribute 'extends'
FAILED test/parse_test.py::ParseTest::test_redeclare_component_in_declaration - AttributeError: 'ComponentRef' object has no attribute 'extends'
FAILED test/parse_test.py::ParseTest::test_redeclare_component_in_extends - AttributeError: 'ComponentRef' object has no attribute 'extends'
FAILED test/parse_test.py::ParseTest::test_redeclare_component_type_compatibility - AttributeError: 'ComponentRef' object has no attribute 'extends'
FAILED test/parse_test.py::ParseTest::test_redeclare_components - AttributeError: 'ComponentRef' object has no attribute 'extends'
=============================================== 20 failed, 207 passed, 13 skipped, 7 xfailed, 21 warnings in 19.78s ===============================================